const products = [
  {
    name: 'Computer 1',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 5,
    price: 100,
    category: 'Computers',
    images: [{ path: '/images/Computers.jpg' }],
    rating: 5,
    reviewsNumber: 5,
    reviews: [],
    attrs: [{ key: 'color', value: 'blue' }],
  },
  {
    name: 'Computer 2',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 5,
    price: 100,
    category: 'Computers',
    images: [{ path: '/images/Computers.jpg' }],
    rating: 4,
    reviewsNumber: 5,
    reviews: [],
    attrs: [
      { key: 'color', value: 'black' },
      { key: 'RAM', value: '1 TB' },
    ],
  },
  {
    name: 'Computer 3',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 5,
    price: 100,
    category: 'Computers/Laptops/Dell',
    images: [{ path: '/images/Computers.jpg' }],
    rating: 3,
    reviewsNumber: 5,
    reviews: [],
    attrs: [
      { key: 'color', value: 'black' },
      { key: 'RAM', value: '1 TB' },
    ],
  },
  {
    name: 'Computer 4',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 5,
    price: 100,
    category: 'Computers/Laptops/Dell',
    images: [{ path: '/images/Computers.jpg' }],
    rating: 2,
    reviewsNumber: 5,
    reviews: [],
    attrs: [
      { key: 'color', value: 'black' },
      { key: 'RAM', value: '1 TB' },
    ],
  },
  {
    name: 'Computer 5',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 5,
    price: 100,
    category: 'Computers/Laptops/Dell',
    images: [{ path: '/images/Computers.jpg' }],
    rating: 1,
    reviewsNumber: 5,
    reviews: [],
    attrs: [
      { key: 'color', value: 'black' },
      { key: 'RAM', value: '1 TB' },
    ],
  },
  {
    name: 'Tablet 1',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 5,
    price: 100,
    category: 'Tablets',
    images: [{ path: '/images/Tablet.jpg' }],
    rating: 1,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: 'Tablet 2',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 5,
    price: 100,
    category: 'Tablets',
    images: [{ path: '/images/Tablet.jpg' }],
    rating: 2,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: 'Tablet 3',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 5,
    price: 100,
    category: 'Tablets',
    images: [{ path: '/images/Tablet.jpg' }],
    rating: 3,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: 'Tablet 4',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 5,
    price: 100,
    category: 'Tablets',
    images: [{ path: '/images/Tablet.jpg' }],
    rating: 4,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: 'Tablet 5',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 10,
    price: 200,
    category: 'Tablets',
    images: [{ path: '/images/Tablet.jpg' }],
    rating: 5,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: 'Cosmetic 1',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 5,
    price: 100,
    category: 'Cosmetics',
    images: [{ path: '/images/Cosmetic.jpg' }],
    rating: 1,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: 'Cosmetic 2',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 10,
    price: 200,
    category: 'Cosmetics',
    images: [{ path: '/images/Cosmetic.jpg' }],
    rating: 2,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: 'Cosmetic 3',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 15,
    price: 300,
    category: 'Cosmetics',
    images: [{ path: '/images/Cosmetic.jpg' }],
    rating: 3,
    reviewsNumber: 7,
    reviews: [],
  },
  {
    name: 'Cosmetic 4',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 20,
    price: 400,
    category: 'Cosmetics',
    images: [{ path: '/images/Cosmetic.jpg' }],
    rating: 4,
    reviewsNumber: 8,
    reviews: [],
  },
  {
    name: 'Cosmetic 5',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 25,
    price: 500,
    category: 'Cosmetics',
    images: [{ path: '/images/Cosmetic.jpg' }],
    rating: 5,
    reviewsNumber: 9,
    reviews: [],
  },
  {
    name: 'Book 1',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 5,
    price: 100,
    category: 'Books',
    images: [{ path: '/images/Book.jpeg' }],
    rating: 1,
    reviewsNumber: 5,
    reviews: [],
  },
  {
    name: 'Book 2',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 10,
    price: 200,
    category: 'Books',
    images: [{ path: '/images/Book.jpeg' }],
    rating: 2,
    reviewsNumber: 6,
    reviews: [],
  },
  {
    name: 'Book 3',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 15,
    price: 300,
    category: 'Books',
    images: [{ path: '/images/Book.jpeg' }],
    rating: 3,
    reviewsNumber: 7,
    reviews: [],
  },
  {
    name: 'Book 4',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 20,
    price: 400,
    category: 'Books',
    images: [{ path: '/images/Book.jpeg' }],
    rating: 4,
    reviewsNumber: 8,
    reviews: [],
  },
  {
    name: 'Book 5',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 25,
    price: 500,
    category: 'Books',
    images: [{ path: '/images/Book.jpeg' }],
    rating: 5,
    reviewsNumber: 9,
    reviews: [],
  },
  {
    name: 'Car 1',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 25,
    price: 500,
    category: 'Cars',
    images: [{ path: '/images/Car.jpg' }],
    rating: 1,
    reviewsNumber: 9,
    reviews: [],
  },
  {
    name: 'Car 2',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 25,
    price: 500,
    category: 'Cars',
    images: [{ path: '/images/Car.jpg' }],
    rating: 2,
    reviewsNumber: 9,
    reviews: [],
  },
  {
    name: 'Car 3',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 25,
    price: 500,
    category: 'Cars',
    images: [{ path: '/images/Car.jpg' }],
    rating: 3,
    reviewsNumber: 9,
    reviews: [],
  },
  {
    name: 'Car 4',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 25,
    price: 500,
    category: 'Cars',
    images: [{ path: '/images/Car.jpg' }],
    rating: 4,
    reviewsNumber: 9,
    reviews: [],
  },
  {
    name: 'Car 5',
    description:
      'Product Description Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni ipsa ducimus architecto explicabo id accusantium nihil exercitationem autem porro esse.',
    count: 25,
    price: 500,
    category: 'Cars',
    images: [{ path: '/images/Car.jpg' }],
    rating: 5,
    reviewsNumber: 9,
    reviews: [],
  },
];

module.exports = products;
